-- ============================================
-- Supply Management System - Oracle Database Schema
-- ============================================
-- This script creates all tables for the supply chain management system
-- Execute in order: Tables -> Sequences -> Triggers -> Stored Procedures

-- ============================================
-- 1. USERS TABLE - User Authentication & Authorization
-- ============================================
CREATE TABLE USERS (
    USER_ID         VARCHAR2(36) PRIMARY KEY,
    EMAIL           VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(255) NOT NULL,
    FIRST_NAME      VARCHAR2(100) NOT NULL,
    LAST_NAME       VARCHAR2(100) NOT NULL,
    ROLE            VARCHAR2(20) DEFAULT 'VIEWER' CHECK (ROLE IN ('ADMIN', 'MANAGER', 'STAFF', 'VIEWER')),
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    LAST_LOGIN      TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 2. REFRESH_TOKENS TABLE - JWT Refresh Token Management
-- ============================================
CREATE TABLE REFRESH_TOKENS (
    TOKEN_ID        VARCHAR2(36) PRIMARY KEY,
    USER_ID         VARCHAR2(36) NOT NULL,
    TOKEN_HASH      VARCHAR2(255) NOT NULL,
    EXPIRES_AT      TIMESTAMP NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REVOKED         NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_REFRESH_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- ============================================
-- 3. SUPPLIERS TABLE - Supplier Master Data
-- ============================================
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID     VARCHAR2(36) PRIMARY KEY,
    SUPPLIER_CODE   VARCHAR2(20) NOT NULL UNIQUE,
    SUPPLIER_NAME   VARCHAR2(255) NOT NULL,
    CONTACT_PERSON  VARCHAR2(100),
    EMAIL           VARCHAR2(255),
    PHONE           VARCHAR2(50),
    ADDRESS_LINE1   VARCHAR2(255),
    ADDRESS_LINE2   VARCHAR2(255),
    CITY            VARCHAR2(100),
    STATE           VARCHAR2(100),
    COUNTRY         VARCHAR2(100) DEFAULT 'Sri Lanka',
    POSTAL_CODE     VARCHAR2(20),
    RATING          NUMBER(2,1) DEFAULT 0 CHECK (RATING >= 0 AND RATING <= 5),
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),
    PAYMENT_TERMS   VARCHAR2(50) DEFAULT 'NET30',
    TAX_ID          VARCHAR2(50),
    CREATED_BY      VARCHAR2(36),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SUPPLIER_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 4. PRODUCT_CATEGORIES TABLE - Product Categorization
-- ============================================
CREATE TABLE PRODUCT_CATEGORIES (
    CATEGORY_ID     VARCHAR2(36) PRIMARY KEY,
    CATEGORY_NAME   VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(500),
    PARENT_ID       VARCHAR2(36),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID)
);

-- ============================================
-- 5. PRODUCTS TABLE - Product Master Data
-- ============================================
CREATE TABLE PRODUCTS (
    PRODUCT_ID      VARCHAR2(36) PRIMARY KEY,
    SKU             VARCHAR2(50) NOT NULL UNIQUE,
    PRODUCT_NAME    VARCHAR2(255) NOT NULL,
    DESCRIPTION     CLOB,
    CATEGORY_ID     VARCHAR2(36),
    UNIT_OF_MEASURE VARCHAR2(20) DEFAULT 'UNIT',
    UNIT_PRICE      NUMBER(15,2) DEFAULT 0.00,
    COST_PRICE      NUMBER(15,2) DEFAULT 0.00,
    MIN_STOCK_LEVEL NUMBER(10) DEFAULT 0,
    MAX_STOCK_LEVEL NUMBER(10) DEFAULT 999999,
    REORDER_POINT   NUMBER(10) DEFAULT 10,
    REORDER_QTY     NUMBER(10) DEFAULT 100,
    LEAD_TIME_DAYS  NUMBER(5) DEFAULT 7,
    WEIGHT_KG       NUMBER(10,3),
    DIMENSIONS      VARCHAR2(100),
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED')),
    CREATED_BY      VARCHAR2(36),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_PRODUCT_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 6. SUPPLIER_PRODUCTS TABLE - Supplier-Product Relationship
-- ============================================
CREATE TABLE SUPPLIER_PRODUCTS (
    SUPPLIER_PRODUCT_ID VARCHAR2(36) PRIMARY KEY,
    SUPPLIER_ID     VARCHAR2(36) NOT NULL,
    PRODUCT_ID      VARCHAR2(36) NOT NULL,
    SUPPLIER_SKU    VARCHAR2(50),
    UNIT_COST       NUMBER(15,2),
    MIN_ORDER_QTY   NUMBER(10) DEFAULT 1,
    LEAD_TIME_DAYS  NUMBER(5),
    IS_PREFERRED    NUMBER(1) DEFAULT 0,
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SP_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT FK_SP_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT UK_SUPPLIER_PRODUCT UNIQUE (SUPPLIER_ID, PRODUCT_ID)
);

-- ============================================
-- 7. WAREHOUSES TABLE - Warehouse Locations
-- ============================================
CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID    VARCHAR2(36) PRIMARY KEY,
    WAREHOUSE_CODE  VARCHAR2(20) NOT NULL UNIQUE,
    WAREHOUSE_NAME  VARCHAR2(255) NOT NULL,
    WAREHOUSE_TYPE  VARCHAR2(50) DEFAULT 'DISTRIBUTION' CHECK (WAREHOUSE_TYPE IN ('DISTRIBUTION', 'MANUFACTURING', 'RETAIL', 'COLD_STORAGE', 'HAZMAT')),
    ADDRESS_LINE1   VARCHAR2(255),
    ADDRESS_LINE2   VARCHAR2(255),
    CITY            VARCHAR2(100),
    STATE           VARCHAR2(100),
    COUNTRY         VARCHAR2(100) DEFAULT 'Sri Lanka',
    POSTAL_CODE     VARCHAR2(20),
    LATITUDE        NUMBER(10,7),
    LONGITUDE       NUMBER(10,7),
    TOTAL_CAPACITY  NUMBER(15) DEFAULT 0,
    USED_CAPACITY   NUMBER(15) DEFAULT 0,
    MANAGER_ID      VARCHAR2(36),
    PHONE           VARCHAR2(50),
    EMAIL           VARCHAR2(255),
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_WAREHOUSE_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 8. INVENTORY TABLE - Stock Levels per Warehouse
-- ============================================
CREATE TABLE INVENTORY (
    INVENTORY_ID    VARCHAR2(36) PRIMARY KEY,
    PRODUCT_ID      VARCHAR2(36) NOT NULL,
    WAREHOUSE_ID    VARCHAR2(36) NOT NULL,
    QUANTITY_ON_HAND NUMBER(15) DEFAULT 0,
    QUANTITY_RESERVED NUMBER(15) DEFAULT 0,
    QUANTITY_AVAILABLE NUMBER(15) GENERATED ALWAYS AS (QUANTITY_ON_HAND - QUANTITY_RESERVED) VIRTUAL,
    LAST_COUNTED_AT TIMESTAMP,
    LAST_RECEIVED_AT TIMESTAMP,
    LAST_SHIPPED_AT TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INV_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_INV_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT UK_PRODUCT_WAREHOUSE UNIQUE (PRODUCT_ID, WAREHOUSE_ID)
);

-- ============================================
-- 9. PURCHASE_ORDERS TABLE - PO Headers
-- ============================================
CREATE TABLE PURCHASE_ORDERS (
    PO_ID           VARCHAR2(36) PRIMARY KEY,
    PO_NUMBER       VARCHAR2(30) NOT NULL UNIQUE,
    SUPPLIER_ID     VARCHAR2(36) NOT NULL,
    WAREHOUSE_ID    VARCHAR2(36) NOT NULL,
    ORDER_DATE      DATE DEFAULT SYSDATE,
    EXPECTED_DATE   DATE,
    STATUS          VARCHAR2(30) DEFAULT 'DRAFT' CHECK (STATUS IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')),
    PRIORITY        VARCHAR2(20) DEFAULT 'NORMAL' CHECK (PRIORITY IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    SUBTOTAL        NUMBER(15,2) DEFAULT 0.00,
    TAX_AMOUNT      NUMBER(15,2) DEFAULT 0.00,
    SHIPPING_COST   NUMBER(15,2) DEFAULT 0.00,
    TOTAL_AMOUNT    NUMBER(15,2) DEFAULT 0.00,
    CURRENCY        VARCHAR2(10) DEFAULT 'LKR',
    NOTES           CLOB,
    CREATED_BY      VARCHAR2(36),
    APPROVED_BY     VARCHAR2(36),
    APPROVED_AT     TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PO_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT FK_PO_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID),
    CONSTRAINT FK_PO_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_PO_APPROVER FOREIGN KEY (APPROVED_BY) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 10. PO_LINE_ITEMS TABLE - PO Details
-- ============================================
CREATE TABLE PO_LINE_ITEMS (
    LINE_ITEM_ID    VARCHAR2(36) PRIMARY KEY,
    PO_ID           VARCHAR2(36) NOT NULL,
    PRODUCT_ID      VARCHAR2(36) NOT NULL,
    LINE_NUMBER     NUMBER(5) NOT NULL,
    QUANTITY_ORDERED NUMBER(15) NOT NULL,
    QUANTITY_RECEIVED NUMBER(15) DEFAULT 0,
    UNIT_PRICE      NUMBER(15,2) NOT NULL,
    LINE_TOTAL      NUMBER(15,2) GENERATED ALWAYS AS (QUANTITY_ORDERED * UNIT_PRICE) VIRTUAL,
    STATUS          VARCHAR2(30) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')),
    NOTES           VARCHAR2(500),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LINE_PO FOREIGN KEY (PO_ID) REFERENCES PURCHASE_ORDERS(PO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LINE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT UK_PO_LINE UNIQUE (PO_ID, LINE_NUMBER)
);

-- ============================================
-- 11. INBOUND_SHIPMENTS TABLE - Shipment Records
-- ============================================
CREATE TABLE INBOUND_SHIPMENTS (
    SHIPMENT_ID     VARCHAR2(36) PRIMARY KEY,
    SHIPMENT_NUMBER VARCHAR2(30) NOT NULL UNIQUE,
    PO_ID           VARCHAR2(36) NOT NULL,
    CARRIER_NAME    VARCHAR2(100),
    TRACKING_NUMBER VARCHAR2(100),
    SHIP_DATE       DATE,
    EXPECTED_ARRIVAL DATE,
    ACTUAL_ARRIVAL  DATE,
    STATUS          VARCHAR2(30) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', 'RETURNED')),
    NOTES           CLOB,
    RECEIVED_BY     VARCHAR2(36),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SHIP_PO FOREIGN KEY (PO_ID) REFERENCES PURCHASE_ORDERS(PO_ID),
    CONSTRAINT FK_SHIP_RECEIVER FOREIGN KEY (RECEIVED_BY) REFERENCES USERS(USER_ID)
);

-- ============================================
-- 12. SHIPMENT_ITEMS TABLE - Items in Shipment
-- ============================================
CREATE TABLE SHIPMENT_ITEMS (
    SHIPMENT_ITEM_ID VARCHAR2(36) PRIMARY KEY,
    SHIPMENT_ID     VARCHAR2(36) NOT NULL,
    LINE_ITEM_ID    VARCHAR2(36) NOT NULL,
    QUANTITY_SHIPPED NUMBER(15) NOT NULL,
    QUANTITY_RECEIVED NUMBER(15) DEFAULT 0,
    CONDITION       VARCHAR2(30) DEFAULT 'GOOD' CHECK (CONDITION IN ('GOOD', 'DAMAGED', 'DEFECTIVE', 'MISSING')),
    NOTES           VARCHAR2(500),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SHIPITEM_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES INBOUND_SHIPMENTS(SHIPMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHIPITEM_LINEITEM FOREIGN KEY (LINE_ITEM_ID) REFERENCES PO_LINE_ITEMS(LINE_ITEM_ID)
);

-- ============================================
-- 13. INVENTORY_TRANSACTIONS TABLE - Stock Movement History
-- ============================================
CREATE TABLE INVENTORY_TRANSACTIONS (
    TRANSACTION_ID  VARCHAR2(36) PRIMARY KEY,
    INVENTORY_ID    VARCHAR2(36) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(30) NOT NULL CHECK (TRANSACTION_TYPE IN ('RECEIPT', 'ISSUE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', 'RETURN', 'WRITE_OFF')),
    REFERENCE_TYPE  VARCHAR2(30),
    REFERENCE_ID    VARCHAR2(36),
    QUANTITY        NUMBER(15) NOT NULL,
    PREVIOUS_QTY    NUMBER(15),
    NEW_QTY         NUMBER(15),
    UNIT_COST       NUMBER(15,2),
    REASON          VARCHAR2(255),
    PERFORMED_BY    VARCHAR2(36),
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INVTX_INVENTORY FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY(INVENTORY_ID),
    CONSTRAINT FK_INVTX_USER FOREIGN KEY (PERFORMED_BY) REFERENCES USERS(USER_ID)
);

-- ============================================
-- Create Sequences for Auto-Numbering
-- ============================================
CREATE SEQUENCE SEQ_PO_NUMBER START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SHIPMENT_NUMBER START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SUPPLIER_CODE START WITH 1000 INCREMENT BY 1 NOCACHE;

-- ============================================
-- Create Indexes for Performance
-- ============================================
CREATE INDEX IDX_SUPPLIER_STATUS ON SUPPLIERS(STATUS);
CREATE INDEX IDX_PRODUCT_SKU ON PRODUCTS(SKU);
CREATE INDEX IDX_PRODUCT_CATEGORY ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IDX_PRODUCT_STATUS ON PRODUCTS(STATUS);
CREATE INDEX IDX_INVENTORY_PRODUCT ON INVENTORY(PRODUCT_ID);
CREATE INDEX IDX_INVENTORY_WAREHOUSE ON INVENTORY(WAREHOUSE_ID);
CREATE INDEX IDX_PO_STATUS ON PURCHASE_ORDERS(STATUS);
CREATE INDEX IDX_PO_SUPPLIER ON PURCHASE_ORDERS(SUPPLIER_ID);
CREATE INDEX IDX_PO_DATE ON PURCHASE_ORDERS(ORDER_DATE);
CREATE INDEX IDX_SHIPMENT_STATUS ON INBOUND_SHIPMENTS(STATUS);
CREATE INDEX IDX_SHIPMENT_PO ON INBOUND_SHIPMENTS(PO_ID);
CREATE INDEX IDX_INVTX_DATE ON INVENTORY_TRANSACTIONS(TRANSACTION_DATE);
CREATE INDEX IDX_INVTX_TYPE ON INVENTORY_TRANSACTIONS(TRANSACTION_TYPE);

COMMIT;
